### ISSUE TITLE
Adding a new layer does not work in Project Builder

### ISSUE THREAD

**Issue by iibrahimli** [microsoft/satellite-imagery-labeling-tool#17]
Hi. I have deployed the application on Kubernetes like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silt
  template:
    metadata:
      labels:
        app: silt
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt update
              apt install -y git
              SILT_DIR=/usr/share/nginx/html/satellite-imagery-labeling-tool
              if [ ! -d $SILT_DIR ]; then
                git clone -b v2.0.3 --depth 1 https://github.com/microsoft/satellite-imagery-labeling-tool.git $SILT_DIR
              fi
              nginx -g "daemon off;"
```

I can access the application, but in the second step of project creation workflow the (`+Add new layer(s)` button does not work. No dialogue window is opened, and I can't see any relevant errors in the developer console. I do not have an Azure account, and intend to use custom TIF tiles (Based on discussion in previous issues the application should work without an Azure account).

Appreciate any pointers, thanks in advance.
